### ISSUE TITLE
To Compat The JSON Object Of JavaScript Syntax.

### ISSUE THREAD

**Issue by litesky** [xphh/easyjson#1]
I think It would be better to use this pattern ([[%s_['"]?(%w+)['"]?%s_:]]) in the function(find_key).

http://wiki.lazarus.freepascal.org/JSON#The_Javascript_syntax

**Comment by xphh** [comment]
Sorry for seeing this issue just now.

I have seen the JSON syntax for JavaScript in that page. Honestly to say, it's ugly. I don't want to compat it yet. Maybe you can compat it in your fork code.
